script: mvn -P generator -P release package

deploy:
- provider: releases
  api_key:
    secure: D3RtTNPe5Ve9uUFGbZlWd7UMXCmaQ4Qc5c5vDjr4QHltyLAAy4sEEazE12OTMyq+5feMGAVynG3wJkna/2RQSk0goN93OoKQ8VVqiEcIOCyvZOnHwnIAqpNtZbxYHEKOl1zYqr3nQIj8tCvLhQop/JhLTsMSnXvb0tn7HUXd1AqSoz+Gdq16Tk70WO9potZvVxq+Y6OZXlT93SzIhK9K0krX7kqdPT1Pxcte8z6PMlt6CtU6OM694VxRQPw5/VFHRYFaAaORvis1qGUk2f2OxtwEf0K2IBiIhYEIPoXJa6KX7BBTE1LviRByhdRTVBDLwU9GE+jPcn/CcoMVT/TC8m5E3D8CBc+3bwscKxGRRFsOtvKyWXro4JQiw4h41sWi6hyyFMplggfswWXMhH1sQ+6iZsWnIxsxAADvBckYpuTwbLEvfTY6FSx2KmikH7J1/cxIny/6I9pNzyNPYB8BdhqxCNHPbxlmdwBsPmqOQDD6au46oPEijgduUlMd/M4b9/mG01dTIza+JDYInRGpQvm4ozPTBrlbUq5MDAE+8f6gU0FPU+7MzXrHWIIeb/3oncgShqyy/LCpU+YaJ7q7MN4n8nqcHV1qsS5IP986zdyOqMl8H9UF1R1C5EM6EyR1U3PI3qYEl+C+5XeS9geWDCk0kqmvVwZ1uuGfdCa21RA=
  file_glob: true
  skip_cleanup: true
  file: llrp4j-distribution/target/llrp4j-onejar-*.jar
  on:
    tags: true
- provider: script
  script: mvn deploy -P generator -P release -s ./.travis.maven-settings.xml
  on:
    tags: true

env:
  global:
  - BINTRAY_USER: kenwenzel
  - secure: EcBRVsg0EzWY5sfXGtXvFCafoO0YVk91WIhBtp39gMHtuFYg/JrvrDLej5x4S1FAkSBLNke9SSE1bl+XeYo6GK+NSF3RcfQzz7aIU4QhPB6xwX5oRPzvXBHb74lDxLUNXh0keTg7pXmIWXnRzRSkaYqt0KFCU1Opwu5jZfv3neYuYc3jZdgjuYDk8g5158k7fXhXlAds93G+ungjYTECS5AWi68pEoTKV4BMgnfB3QaoiYgSWak+sqSrdqs7o5kwsUwFSd5mxbjCL1+3o1YIZz859cIeYb+2RzRbFjBRuWWhXk+9vc70dgCPaLbj37hgbU4QDkGAjAqWHPo8KGcfynLuzAv45W0BOeyXX74uBTVwPh8pq+7Mb209DVjwm4h5k7mOpiKANSkB+ema8Hi58cv0AxQsgP+vOFDksNWsrwWEGX1QEKd+YaZtcSDZhWOd2WpH1lv4gtIe5zzigVJXImD+mcvYK4PdQ5h8TAAAoq+unKnrpZartaVGU00S8Lsg6ABiz7ekULkqZTGr8BBtK94OM4OFnwuSUFB01IfyKvDulWo956UR90xakSw99FYNvV/Lt/kdD3UDZDEGub7Zj4CeGRu53Lz862/oWN5jymwVOULoSzlKG8xRmZGnmIde6qzlH9CKM/fYa+rzkRZWPQWjxA2rvxZXU0/yCwVw6n4=
